# INFLUX_DB

INFLUX_HOST = "air.eng.utah.edu"

INFLUX_PORT = 8086

INFLUX_USERNAME = "pgoffin"

INFLUX_PASSWORD = "F2fZsdyj2MZR"

INFLUX_POLLING_DATABASE = "defaultdb"
INFLUX_AIRU_DATABASE = "airU"
INFLUX_AIRU_LOGGING_SENSOR_CONNECTION_DATABASE = "sensorLog"

SSL = True

INFLUX_POLLING_MEASUREMENT = "airQuality"   # not used yet

INFLUX_AIRU_LATITUDE_MEASUREMENT = "latitude"
INFLUX_AIRU_LONGITUDE_MEASUREMENT = "longitude"
INFLUX_AIRU_PM25_MEASUREMENT = "pm25"
INFLUX_AIRU_LOGGING_SENSOR_MEASUREMENT = "logSensorConnection"


# MONGO_DB

MONGO_HOST = "localhost"

MONGO_USER = "airu"

MONGO_PASSWORD = "zZ89M9"

MONGO_PORT = 27017

MONGO_DATABASE = "airudb"


# TWILIO

TWILIO_ACCOUNT_SID = "AC01e5bf76b6807cbf77f33ca5794a886d"   # Your Account SID from twilio.com/console

TWILIO_AUTH_TOKEN  = "afb9faad69355bcdc4d77fff54b95cee" # Your Auth Token from twilio.com/console

PHONE_NUMBER_TO_SEND_MESSAGE = "+13852357676 "   # the bought phone number on twilio


# MODELING

CURRENT_MODEL_VERSION = "1.0.0"
CURRENT_GRID_VERSION = 4

NUMBER_GRID_CELLS_LAT = 35
NUMBER_GRID_CELLS_LONG = 48

#CHARACTERISTIC_TIME_LENGTH = 7.5732

METADATA_TYPE_HIGH_UNCERTAINTY  = "timeSlicedEstimates_high"
METADATA_TYPE_LOW_UNCERTAINTY = "timeSlicedEstimates_low"

BOTTOM_LEFT_CORNER_LAT = 40.598850
BOTTOM_LEFT_CORNER_LONG = -112.001349
TOP_RIGHT_CORNER_LAT = 40.810476
TOP_RIGHT_CORNER_LONG = -111.713403


# MAIL

MAIL_SERVER = "mail.sci.utah.edu"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = "aqandu@sci.utah.edu"
MAIL_PASSWORD = "clean_air"
MAIL_DEFAULT_SENDER = "aqandu@sci.utah.edu"


# SENTRY

SENTRY = "https://73c903519f97462789e4e6c27e7f893a:13b82c712e794f60b56893ea96db2825@sentry.io/242656"


